<nav class="nav-inferior fixed-bottom navbar-light">
        <div class="container-fluid h-100 max-width-mobile">
            <div class="row h-100 text-center align-items-center">
                
                <!-- Pestaña Académica / Cursadas -->
                <div class="col-4 h-100">
                    <a href="<?= PUBLIC_PATH ?>academico" class="nav-link active">
                        <div class="icon-wrapper">📊</div>
                        <span>Cursada</span>
                    </a>
                </div>
                
                <!-- Pestaña Movilidad / UNO-Pool -->
                <div class="col-4 h-100">
                    <a href="<?= PUBLIC_PATH ?>pool" class="nav-link">
                        <div class="icon-wrapper">🚗</div>
                        <span>UNO-Pool</span>
                    </a>
                </div>
                
                <!-- Pestaña Documentos / Apuntes -->
                <div class="col-4 h-100">
                    <a href="<?= PUBLIC_PATH ?>documentos" class="nav-link">
                        <div class="icon-wrapper">📂</div>
                        <span>Apuntes</span>
                    </a>
                </div>

            </div>
        </div>
    </nav>