<div class="container mt-4" style="max-width: 600px;">
    <div class="card card-login bg-white p-3">
        <div class="card-body">
            <h3 class="fw-bold text-dark mb-4"><?= $materia->id ? 'Editar Materia' : 'Nueva Materia' ?></h3>

            <form action="<?= PUBLIC_PATH ?>admin_materias/guardar" method="POST">
                
                <?= Form::hidden('materia.id') ?>
                <?= Form::hidden('materia.creado_at') ?>

                <div class="mb-3">
                    <label class="form-label small fw-semibold text-secondary">Código de la Materia</label>
                    <input type="text" name="materia[codigo]" class="form-control form-control-lg rounded-3 fs-6" required value="<?= $materia->codigo ?>">
                    
                </div>

                <div class="mb-3">
                    <label class="form-label small fw-semibold text-secondary">Nombre de la Materia</label>
                    <input type="text" name="materia[nombre]" class="form-control form-control-lg rounded-3 fs-6" required value="<?= $materia->nombre ?>">
                </div>

                <div class="mb-4">
                    <div class="form-check form-switch p-0 d-flex align-items-center justify-content-between">
                        <label class="form-check-label fw-semibold text-secondary" for="promocionableSwitch">
                            ¿La materia es promocionable?
                        </label>
                        <input class="form-check-input ms-0" type="checkbox" role="switch" id="promocionableSwitch" name="materia[promocionable]" value="1" style="width: 2.5em; height: 1.25em;" <?= ($materia->promocionable == 1 || !$materia->id) ? 'checked' : '' ?>>
                    </div>
                </div>

                <div class="d-flex gap-2">
                    <button type="submit" class="btn btn-uno w-100 rounded-3 py-2.5 fs-6 shadow-sm">
                        Guardar Materia
                    </button>
                    <a href="<?= PUBLIC_PATH ?>admin_materias" class="btn btn-light w-50 rounded-3 py-2.5 fs-6 border">
                        Cancelar
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>